spring.application.name=tienda

#Se define el puerto por donde se escucha el servidor web
server.port=80

#Se define el formato del log fecha/hora
logging.pattern.dateformat=hh:mm

#Se evita mostrar el banner SPRING en el log
spring.main.banner-mode=off

#Se evita el uso de cache en desarrollo y se evita en producción
spring.thymeleaf.cache=false